dependency check for dashboard

diff --git a/.github/workflows/fossology-spdx3.yml b/.github/workflows/fossology-spdx3.yml
--- a/.github/workflows/fossology-spdx3.yml
+++ b/.github/workflows/fossology-spdx3.yml
@@ -1,30 +1,100 @@
+# name: Software Composition Analysis
+
+# on:
+#   push:
+
+# permissions:
+#   contents: read
+#   actions: write
+
+# jobs:
+#   sca:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+
+#       - name: Run FOSSology analysis
+#         id: fossology
+#         uses: shatakshisgtiwari-jpg/fossology-action@main
+#         with:
+#           scan_mode: "repo"
+#           scanners: "nomos ojo copyright"
+#           report_format: "SPDX3_JSON"
+#           dashboard: true
+#           dashboard_charts: true
+#           dashboard_risk: true
+#           dashboard_unknown: true
+
+#       - name: Upload Scan Results Artifact
+#         if: success() || failure()
+#         uses: actions/upload-artifact@v4.6.2
+#         with:
+#           name: Fossology scan results
+#           path: results/
+
+
+
+
 name: Software Composition Analysis
 
 on:
   push:
+
 
 permissions:
   contents: read
   actions: write
 
 jobs:
-  sca:
+  sbom:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+
+      - name: Install cdxgen
+        run: npm install -g @cyclonedx/cdxgen
+
+      - name: Generate CDX SBOM
+        run: cdxgen -r -o sbom.json --spec-version 1.6 --format json
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: sbom
+          path: sbom.json
+          if-no-files-found: error
+
+  sca:
+    runs-on: ubuntu-latest
+    needs: sbom
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download SBOM
+        uses: actions/download-artifact@v4
+        with:
+          name: sbom
 
       - name: Run FOSSology analysis
         id: fossology
         uses: shatakshisgtiwari-jpg/fossology-action@main
         with:
-          scan_mode: "repo"
+          scan_mode: "scan-only-deps"
           scanners: "nomos ojo copyright"
-          report_format: "SPDX3_JSON"
-          dashboard: true
-          dashboard_charts: true
-          dashboard_risk: true
-          dashboard_unknown: true
+          report_format: "SPDX_JSON"
+          sbom_path: "sbom.json"
 
       - name: Upload Scan Results Artifact
         if: success() || failure()
@@ -33,4 +103,74 @@ jobs:
           name: Fossology scan results
           path: results/
 
-# For more information on the FOSSology GitHub Action, please refer to the documentation:
+
+
+
+
+
+# name: Software Composition Analysis
+
+# on:
+#   push:
+
+
+# permissions:
+#   contents: read
+#   actions: write
+
+# jobs:
+#   sbom:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+
+#       - uses: actions/setup-java@v4
+#         with:
+#           distribution: 'temurin'
+#           java-version: '21'
+
+#       - uses: actions/setup-node@v4
+#         with:
+#           node-version: '20'
+
+#       - name: Install cdxgen
+#         run: npm install -g @cyclonedx/cdxgen
+
+#       - name: Generate CDX SBOM
+#         run: cdxgen -r -o sbom.json --spec-version 1.6 --format json
+
+#       - uses: actions/upload-artifact@v4
+#         with:
+#           name: sbom
+#           path: sbom.json
+#           if-no-files-found: error
+
+#   sca:
+#     runs-on: ubuntu-latest
+#     needs: sbom
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+
+#       - name: Download SBOM
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: sbom
+
+#       - name: Run FOSSology analysis
+#         id: fossology
+#         uses: shatakshisgtiwari-jpg/fossology-action@main
+#         with:
+#           scan_mode: "scan-only-deps"
+#           scanners: "nomos ojo copyright"
+#           report_format: "SPDX_JSON"
+#           sbom_path: "sbom.json"
+
+#       - name: Upload Scan Results Artifact
+#         if: success() || failure()
+#         uses: actions/upload-artifact@v4.6.2
+#         with:
+#           name: Fossology scan results
+#           path: results/
